# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportWindow(object):
    def setupUi(self, ReportWindow):
        ReportWindow.setObjectName("ReportWindow")
        ReportWindow.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(ReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Report_to_A_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Report_to_A_Button.setGeometry(QtCore.QRect(40, 40, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        self.Report_to_A_Button.setFont(font)
        self.Report_to_A_Button.setObjectName("Report_to_A_Button")
        self.Report_to_B_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Report_to_B_Button.setGeometry(QtCore.QRect(40, 110, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        self.Report_to_B_Button.setFont(font)
        self.Report_to_B_Button.setObjectName("Report_to_B_Button")
        self.Report_to_C_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Report_to_C_Button.setGeometry(QtCore.QRect(40, 180, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        self.Report_to_C_Button.setFont(font)
        self.Report_to_C_Button.setObjectName("Report_to_C_Button")
        ReportWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReportWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        ReportWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReportWindow)
        self.statusbar.setObjectName("statusbar")
        ReportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReportWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportWindow)

    def retranslateUi(self, ReportWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportWindow.setWindowTitle(_translate("ReportWindow", "报告窗口"))
        self.Report_to_A_Button.setText(_translate("ReportWindow", "报告给经理A"))
        self.Report_to_B_Button.setText(_translate("ReportWindow", "报告给经理B"))
        self.Report_to_C_Button.setText(_translate("ReportWindow", "报告给经理C"))
